### ISSUE TITLE
Error when installing with the Qt MaintenanceTool for Qt 5.14

### ISSUE THREAD

**Issue by AmyXS** [Skycoder42/QtModules#2]
Hi There,

Really appreciate your work here! 

I tried to install this library using the MaintenanceTool. but could not find your repo after adding the URL.

I got this error message:
Cannot find missing dependency "qt.qt5.5140.src" for "qt.qt5.5140.skycoder42.jsonserializer.src".

Any idea how to fix this?

Cheers,

Amy

**Comment by Skycoder42** [comment]
Are you using the online installer? It does not work with the offline installer

**Comment by AmyXS** [comment]
Oh it works with online installer thanks!
